# Generated by Django 5.0.2 on 2024-02-15 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('location', models.CharField(choices=[('Block A', 'Block A'), ('Block B', 'Block B'), ('Block C', 'Block C'), ('Block D', 'Block D'), ('Block E', 'Block E')], max_length=20, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('reg_no', models.CharField(max_length=10, unique=True)),
                ('rank', models.CharField(choices=[('Lecturer', 'Lecturer'), ('Assistant Professor', 'Assistant Professor'), ('Professor', 'Professor'), ('Head of The Department', 'Head of The Department')], max_length=40, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=3000, null=True)),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.department')),
            ],
        ),
    ]
