# Generated by Django 5.0.1 on 2024-01-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accecpted', 'Accecpted')], default='Pending', max_length=40, null=True),
        ),
    ]
