# Generated by Django 5.0.2 on 2024-02-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the department was created.'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, help_text='Enter a description of the department.', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='email',
            field=models.CharField(help_text="Enter the department's email address.", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='location',
            field=models.CharField(choices=[('Block A', 'Block A'), ('Block B', 'Block B'), ('Block C', 'Block C'), ('Block D', 'Block D'), ('Block E', 'Block E')], help_text="Select the department's location.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text="Enter the department's name.", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='phone',
            field=models.CharField(help_text="Enter the department's phone number.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='rank',
            field=models.IntegerField(blank=True, help_text="Enter the department's rank.", null=True),
        ),
    ]
