# Generated by Django 5.0.1 on 2024-02-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_student_dob_alter_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('location', models.CharField(choices=[('Block A', 'Block A'), ('Block B', 'Block B'), ('Block C', 'Block C'), ('Block D', 'Block D'), ('Block E', 'Block E')], max_length=20, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
    ]
