# Generated by Django 5.0.1 on 2024-02-06 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_student_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='Admin', max_length=30)),
                ('receiver', models.CharField(max_length=20, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('reg_no', models.CharField(max_length=10, unique=True)),
                ('rank', models.CharField(choices=[('Lecturer', 'Lecturer'), ('Assistant Professor', 'Assistant Professor'), ('Professor', 'Professor'), ('Head of The Department', 'Head of The Department')], max_length=40, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=3000, null=True)),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.department')),
            ],
        ),
    ]
