# Generated by Django 5.0.2 on 2024-02-25 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_department_date_created_and_more'),
        ('base', '0008_delete_adminnotice_remove_student_dept_and_more'),
    ]

    operations = [
    ]
